### ISSUE TITLE
addPluginJavascriptFile ignores plugin name

### ISSUE THREAD

**Issue by matthiaz** [qcubed/application#7]
ControlBase method addPluginJavascriptFile

This was modified so we no longer allow relative urls. But this causes plugins to break.

You can no longer do: 
    
     $objControl->AddPluginJavascriptFile('bootstrap', 'qshim.js'); 

The addPluginJavascript now ignores the first parameter. Can we figure out how not to ignore it and build the full url for the user? We know the path to the plugin, so we should right?

**Comment by spekary** [comment]
For v4, this function should be removed. This function was needed because of the installation process of v1 plugins. Its really not needed any more with composer installing the plugins now. See some of the plugins I ported to v4 for examples of how to add the javascript files for plugins.

Note that the current system works wellf or setting up a development system, but we have not created a good deployment process. As part of deployment, the various assets should be moved to some central place. This is an issue for all deployments of composer type projects, and not just qcubed though. Perhaps some other project out there has solved this?
